services:
  database:
    container_name: postgres
    restart: always
    image: postgres:17.0-alpine3.20
    env_file:
      - ../.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
